version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: helloRedis
      POSTGRES_DB: redis_app
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgres/data
  cache:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  postgres_data: